package com.zillabyte.motherbrain.api;

import java.util.Collection;

import com.zillabyte.motherbrain.flow.MapTuple;
import com.zillabyte.motherbrain.utils.Utils;

import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

public class LocalAPIService implements APIService {

  @Override
  public JSONObject getFlowSettings(String flowName, String authToken) throws APIException {
    JSONObject json = new JSONObject();
    json.put("id", flowName);
    json.put("version", 0);
    return json;
  }

  @Override
  public JSONObject getRelationSettings(String relationName, String authToken) throws APIException {
    return new JSONObject();
  }

  @Override
  public JSONObject getRelationConcretified(String flowId, String sql, String authToken) throws APIException {
    JSONObject params = new JSONObject();
    params.put("relation", sql);
    return RestAPIHelper.post("/relation_backend/concretify_anonymous", params.toString(), authToken);
  }

  @Override
  public JSONObject postRelationSettingsForNextVersion(String relationName, JSONArray jsonSchema, String bufferType, String authToken) throws APIException {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public JSONObject postFlowState(String id, String newState, String authToken) throws APIException {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public JSONObject postFlowRegistration(String id, JSONObject schema, String authToken) throws APIException {
    // TODO Auto-generated method stub
    return null;
  }

  @Override
  public JSONObject appendRelation(String relationId, Collection<MapTuple> buffer, String authToken) throws APIException {
    return Utils.TODO("This is a good place to capture data generated by a sink, and then present it back to the user.  This method should get called if you instantiate the LocalBufferService in the universe");
  }

}
